name = "telimag"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "app_data"
id = "9705add4eab24637b001a71a03bf534e"
preview_id = "16a4ea5336224135a95ef5faf7c9fb96"

[env.production]
vars = { NODE_ENV = "production" }

[[env.production.kv_namespaces]]
binding = "app_data"
id = "9705add4eab24637b001a71a03bf534e"

[env.preview]
vars = { NODE_ENV = "development" }

[[env.preview.kv_namespaces]]
binding = "app_data"
id = "9705add4eab24637b001a71a03bf534e"
